### ISSUE TITLE
Output files contain extra null bytes

### ISSUE THREAD

**Issue by danc86** [FluffyKaon/tomtom-cardio-watch-reader#1]
I noticed that the output files seem to contain extraneous null bytes interspersed throughout the file.

I haven't yet found a tool that can compare the two files. `cmp -l` unfortunately seems to assume that the two files are the same length, so as soon as it sees the first extra null bytes it considers the entire rest of the file to differ. `diff` with `xxd` has the same problem since it's line-based. Anyway from what I can see it is only null bytes and the location seems random.

I guess it might be a buffer sizing issue (copying longer than read or similar). I will try digging into the code soon to see if I can spot anything, but I thought I'd file this first to see if you had any ideas.

Github won't let me attach the files here so I will post some links shortly...

**Comment by danc86** [comment]
Output from Tomtom software: https://www.djc.id.au/2014/tomtom-cardio-watch-reader-%231/Running_17-55-15.ttbin
Output from extract_files: https://www.djc.id.au/2014/tomtom-cardio-watch-reader-%231/91000700.bin

**Comment by danc86** [comment]
In case it gives any hints, the first few extraneous null bytes are at positions:
109
110
154
204
255
306
359
409
459

So roughly every 50 bytes...

**Comment by FluffyKaon** [comment]
Sorry, I can't work on this project anymore. I recommend forking it and making changes on your fork.
